# Generated by Django 4.2.13 on 2024-05-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
