# Generated by Django 4.2.13 on 2024-05-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
