export default {
    products: [],
    categories: [],
    totalProducts: 0,
    selectedValue: 'Relevance',
    selctedCategoryName: " ",
    availableInUsa: false,
    filters: {
      min_price: '',
      max_price: '',
      stock_in_usa: '',
      minimimum_order_quantity: '',
      category__category__category_name: '',
      category__sub_category_name: '',
      product_name__icontains: '',
      manufacturer__location__in: '',
      ordering: '',
      page: 1,
    },
    country_options: [
      { id: 1, name: "Hong Kong S.A.R", selected: false },
      { id: 2, name: "India", selected: false },
      { id: 3, name: "China", selected: false },
      { id: 4, name: "Vietnam", selected: false },
      { id: 5, name: "United States", selected: false },
      { id: 6, name: "Canada", selected: false },
      { id: 7, name: "Australia", selected: false },
      { id: 8, name: "United Kingdom", selected: false },
      { id: 9, name: "Korea, Republic of", selected: false },
    ],
    ordering_options: [
      { id: 1, name: "Relevance", ordering_param: '' },
      { id: 2, name: "Latest", ordering_param: 'created_at' },
      { id: 3, name: "Price Low To High", ordering_param: 'price' },
      { id: 4, name: "Price High To Low", ordering_param: '-price' },
      { id: 5, name: "MOQ Low To High", ordering_param: 'minimum_order_qunatity' },
      { id: 5, name: "Ratings High To Low", ordering_param: '-supplier__rating' },
    ],
  }